package git_test

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/tdawn0-0/git-analyzer/internal/config"
	"github.com/tdawn0-0/git-analyzer/internal/git"
	"github.com/tdawn0-0/git-analyzer/internal/model"
)

func TestParseLogOutput(t *testing.T) {
	const sample = `===COMMIT===
abc123
Alice
alice@example.com
2026-09-10T12:00:00Z
feat: add login
10	2	server/api/login.go
3	0	server/api/login_test.go

===COMMIT===
def456
Bob
bob@example.com
2026-09-11T08:30:00+00:00
fix docs
5	1	docs/guide.md
-	-	assets/logo.png
`

	commits, err := git.ParseLogOutput(sample)
	if err != nil {
		t.Fatal(err)
	}
	if len(commits) != 2 {
		t.Fatalf("commits=%d", len(commits))
	}
	c0 := commits[0]
	if c0.Hash != "abc123" || c0.Author != "Alice" || c0.Email != "alice@example.com" {
		t.Fatalf("meta=%+v", c0)
	}
	if c0.Subject != "feat: add login" {
		t.Fatalf("subject=%q", c0.Subject)
	}
	if !c0.Date.Equal(time.Date(2026, 9, 10, 12, 0, 0, 0, time.UTC)) {
		t.Fatalf("date=%v", c0.Date)
	}
	if len(c0.Files) != 2 || c0.Files[0].Added != 10 || c0.Files[0].Deleted != 2 {
		t.Fatalf("files=%+v", c0.Files)
	}
	if !commits[1].Files[1].Binary {
		t.Fatal("expected binary numstat")
	}
}

func TestAnalyzeRepositoryScoresAndModules(t *testing.T) {
	requireGit(t)
	root := t.TempDir()
	repoDir := filepath.Join(root, "svc")
	initRepo(t, repoDir)

	write := func(rel, body string) {
		p := filepath.Join(repoDir, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("server/api/a.go", "package api\nfunc A() {}\n")
	write("server/api/a_test.go", "package api\nfunc TestA(t *testing.T) {}\n")
	write("docs/readme.md", "# docs\n")
	gitRun(t, repoDir, "add", ".")
	gitRun(t, repoDir, "commit", "-m", "feat(api): add endpoint")

	cfg := config.Defaults()
	cfg.Modules = map[string]config.ModuleDef{
		"api": {Paths: []string{"server/api/**"}, Weight: 1.1, Layer: "backend"},
		"docs": {Paths: []string{"docs/**"}, Weight: 0.9, Layer: "docs"},
	}

	repo, err := git.NewRepository(context.Background(), repoDir)
	if err != nil {
		t.Fatal(err)
	}
	res := git.AnalyzeRepository(context.Background(), repo, cfg, git.AnalyzeOptions{})
	if res.Status != model.StatusComplete {
		t.Fatalf("status=%s err=%v msg=%s", res.Status, res.Err, res.Message)
	}
	if len(res.Changes) < 2 { // init + feat
		t.Fatalf("changes=%d", len(res.Changes))
	}
	var feat *model.ChangeUnit
	for i := range res.Changes {
		if strings.HasPrefix(res.Changes[i].Message, "feat") {
			feat = &res.Changes[i]
			break
		}
	}
	if feat == nil {
		t.Fatal("feat commit not found")
	}
	if feat.Type != model.ChangeTypeFeat {
		t.Fatalf("type=%s", feat.Type)
	}
	if feat.Score.Final <= 0 || feat.Score.SizeScore <= 0 {
		t.Fatalf("score=%+v", feat.Score)
	}
	if len(feat.Modules) == 0 {
		t.Fatalf("expected modules, got %v", feat.Modules)
	}
	if feat.Score.QualityFactor < 1.05 {
		t.Fatalf("expected test bonus, quality=%v", feat.Score.QualityFactor)
	}
}

func TestAnalyzeGeneratedFiltering(t *testing.T) {
	requireGit(t)
	root := t.TempDir()
	repoDir := filepath.Join(root, "genrepo")
	initRepo(t, repoDir)

	lock := filepath.Join(repoDir, "package-lock.json")
	if err := os.WriteFile(lock, []byte(strings.Repeat("x\n", 100)), 0o644); err != nil {
		t.Fatal(err)
	}
	gen := filepath.Join(repoDir, "pkg", "zz.go")
	if err := os.MkdirAll(filepath.Dir(gen), 0o755); err != nil {
		t.Fatal(err)
	}
	content := "// Code generated by hand. DO NOT EDIT.\npackage pkg\nfunc Z() {}\n"
	if err := os.WriteFile(gen, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	src := filepath.Join(repoDir, "pkg", "hand.go")
	if err := os.WriteFile(src, []byte("package pkg\nfunc Hand() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	gitRun(t, repoDir, "add", ".")
	gitRun(t, repoDir, "commit", "-m", "chore: mix generated")

	repo, err := git.NewRepository(context.Background(), repoDir)
	if err != nil {
		t.Fatal(err)
	}
	res := git.AnalyzeRepository(context.Background(), repo, config.Defaults(), git.AnalyzeOptions{})
	if res.Status != model.StatusComplete {
		t.Fatalf("%s %v", res.Status, res.Err)
	}
	var chore *model.ChangeUnit
	for i := range res.Changes {
		if strings.Contains(res.Changes[i].Message, "mix generated") {
			chore = &res.Changes[i]
			break
		}
	}
	if chore == nil {
		t.Fatal("commit missing")
	}
	if chore.GeneratedAdded == 0 {
		t.Fatalf("expected generated lines excluded, got gen=+%d scoreLines=+%d", chore.GeneratedAdded, chore.AddedLines)
	}
	if chore.AddedLines == 0 {
		t.Fatal("hand.go should still count")
	}
}

func TestBranchUnavailableIsolation(t *testing.T) {
	requireGit(t)
	root := t.TempDir()
	a := filepath.Join(root, "a")
	b := filepath.Join(root, "b")
	initRepo(t, a)
	initRepo(t, b)
	gitRun(t, a, "branch", "release")

	ra, err := git.NewRepository(context.Background(), a)
	if err != nil {
		t.Fatal(err)
	}
	rb, err := git.NewRepository(context.Background(), b)
	if err != nil {
		t.Fatal(err)
	}

	cfg := config.Defaults()
	opts := git.AnalyzeOptions{Branch: "release"}
	resa := git.AnalyzeRepository(context.Background(), ra, cfg, opts)
	resb := git.AnalyzeRepository(context.Background(), rb, cfg, opts)

	if resa.Status != model.StatusComplete {
		t.Fatalf("a status=%s msg=%s", resa.Status, resa.Message)
	}
	if resb.Status != model.StatusSkipped || resb.Message != "branch unavailable" {
		t.Fatalf("b status=%s msg=%s", resb.Status, resb.Message)
	}
	if resb.Err != nil {
		t.Fatalf("skipped should not set Err: %v", resb.Err)
	}
}

func TestLanguageAndModuleMapping(t *testing.T) {
	if got := git.LanguageFromPath("foo/bar.go"); got != "Go" {
		t.Fatalf("%q", got)
	}
	mods := map[string]config.ModuleDef{
		"api":  {Paths: []string{"server/api/**"}, Layer: "backend"},
		"db":   {Paths: []string{"**/migration/**"}, Layer: "database"},
		"web":  {Paths: []string{"frontend/**"}, Layer: "frontend"},
	}
	got := git.MatchModules("server/api/x.go", mods)
	if len(got) != 1 || got[0] != "api" {
		t.Fatalf("%v", got)
	}
	got = git.MatchModules("services/migration/001.sql", mods)
	if len(got) != 1 || got[0] != "db" {
		t.Fatalf("%v", got)
	}
	layers := git.LayersForModules([]string{"api", "db"}, mods)
	if len(layers) != 2 {
		t.Fatalf("%v", layers)
	}
}

func TestInferTypeFallbackInAnalyze(t *testing.T) {
	requireGit(t)
	dir := t.TempDir()
	initRepo(t, dir)
	p := filepath.Join(dir, "foo_test.go")
	if err := os.WriteFile(p, []byte("package main\nfunc TestFoo(t *testing.T) {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	gitRun(t, dir, "add", ".")
	gitRun(t, dir, "commit", "-m", "add coverage")

	repo, err := git.NewRepository(context.Background(), dir)
	if err != nil {
		t.Fatal(err)
	}
	res := git.AnalyzeRepository(context.Background(), repo, config.Defaults(), git.AnalyzeOptions{})
	var found *model.ChangeUnit
	for i := range res.Changes {
		if res.Changes[i].Message == "add coverage" {
			found = &res.Changes[i]
		}
	}
	if found == nil || found.Type != model.ChangeTypeTest {
		t.Fatalf("got %+v", found)
	}
}
