package metrics

import (
	"path/filepath"
	"strings"
)

// Default generated / lock / build path patterns (basename or path fragment checks).
var defaultGeneratedBasenames = map[string]struct{}{
	"package-lock.json": {},
	"pnpm-lock.yaml":    {},
	"yarn.lock":         {},
	"bun.lock":          {},
	"bun.lockb":         {},
	"go.sum":            {},
}

var defaultGeneratedDirNames = map[string]struct{}{
	"node_modules": {},
	"vendor":       {},
	"dist":         {},
	"build":        {},
	"target":       {},
	"generated":    {},
}

var generatedHeaderMarkers = []string{
	"DO NOT EDIT",
	"Generated by",
	"This file is automatically generated",
	"Code generated",
	"AUTO-GENERATED",
	"autogenerated",
}

// IsGeneratedPath reports whether a repo-relative path should be excluded from SizeScore.
func IsGeneratedPath(path string) bool {
	path = filepath.ToSlash(strings.TrimSpace(path))
	if path == "" {
		return false
	}
	base := filepath.Base(path)
	if _, ok := defaultGeneratedBasenames[base]; ok {
		return true
	}
	lower := strings.ToLower(base)
	if strings.HasSuffix(lower, ".min.js") || strings.HasSuffix(lower, ".min.css") ||
		strings.HasSuffix(lower, ".map") {
		return true
	}
	if strings.Contains(lower, ".generated.") {
		return true
	}
	parts := strings.Split(path, "/")
	for _, part := range parts {
		if _, ok := defaultGeneratedDirNames[part]; ok {
			return true
		}
	}
	return false
}

// IsGeneratedContent reports header heuristics for generated sources.
// Only the leading portion of content should be passed (e.g. first 1–2 KiB).
func IsGeneratedContent(content string) bool {
	if content == "" {
		return false
	}
	// Inspect a bounded prefix for markers (case-sensitive for Go's "Code generated" idiom,
	// plus a few case-insensitive common phrases).
	prefix := content
	if len(prefix) > 2048 {
		prefix = prefix[:2048]
	}
	for _, marker := range generatedHeaderMarkers {
		if strings.Contains(prefix, marker) {
			return true
		}
		if strings.Contains(strings.ToLower(prefix), strings.ToLower(marker)) {
			return true
		}
	}
	return false
}

// IsExcludedFromScore is true when path or content indicates generated/ignored artifact.
func IsExcludedFromScore(path, contentPrefix string) bool {
	return IsGeneratedPath(path) || IsGeneratedContent(contentPrefix)
}
